output_dir: models/flux2og_lora/dog
subject_name: dog
unique_token: kqwei
subject_class_map:
  dog: dog

instance_data_root: data/instance
class_data_root: data/class/flux2og
train_text_encoder: false
train_text_encoder_lora: false

train_batch_size: 1