subjects:
  backpack:
    class_name: backpack
    subject_type: object
  backpack_dog:
    class_name: backpack
    subject_type: object
  bear_plushie:
    class_name: stuffed animal
    class_dir_name: stuffed_animal
    subject_type: object
  berry_bowl:
    class_name: bowl
    subject_type: object
  bird:
    class_name: bird
    subject_type: live
  can:
    class_name: can
    subject_type: object
  candle:
    class_name: candle
    subject_type: object
  cat:
    class_name: cat
    subject_type: live
  cat2:
    class_name: cat
    subject_type: live
  clock:
    class_name: clock
    subject_type: object
  colorful_sneaker:
    class_name: sneaker
    subject_type: object
  dog:
    class_name: dog
    subject_type: live
  dog2:
    class_name: dog
    subject_type: live
  dog3:
    class_name: dog
    subject_type: live
  dog5:
    class_name: dog
    subject_type: live
  dog6:
    class_name: dog
    subject_type: live
  dog7:
    class_name: dog
    subject_type: live
  dog8:
    class_name: dog
    subject_type: live
  duck_toy:
    class_name: toy
    subject_type: object
  fancy_boot:
    class_name: boot
    subject_type: object
  grey_sloth_plushie:
    class_name: stuffed animal
    class_dir_name: stuffed_animal
    subject_type: object
  monster_toy:
    class_name: toy
    subject_type: object
  pink_sunglasses:
    class_name: glasses
    subject_type: object
  poop_emoji:
    class_name: toy
    subject_type: object
  rc_car:
    class_name: toy
    subject_type: object
  red_cartoon:
    class_name: red_cartoon
    subject_type: object
  robot_toy:
    class_name: toy
    subject_type: object
  shiny_sneaker:
    class_name: sneaker
    subject_type: object
  teapot:
    class_name: teapot
    subject_type: object
  vase:
    class_name: vase
    subject_type: object
  wolf_plushie:
    class_name: stuffed animal
    class_dir_name: stuffed_animal
    subject_type: object
